spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      authentication-database: admin    
      host: mongolocalhost
      port: 27017
      database: teste
      password: admin
      username: admin